spring:
  thymeleaf:
    cache: false
  application:
    name: eis-web
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://localhost:3306/eis?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: a3873121
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      idle-timeout: 60000
      validation-timeout: 3000
      login-timeout: 5
      maximum-pool-size: 30
      minimum-idle: 10
  redis:
    host:
server:
  port: 8080
logging:
  path: ${user.home}/logs/
  file: ${spring.application.name}.log
  level:
    org.springframework.boot: info
    com.cgcg: debug
    org.hibernate.SQL: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
fileHome: ${user.home}
mybatis:
  configuration:
    map-underscore-to-camel-case: true