spring:
  datasource:
    url: jdbc:mysql://39.99.175.96:3306/eis?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: eis12Pd@
    driverClassName: com.mysql.cj.jdbc.Driver