spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eis?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: eis
    password: TkzhDz37mbHT4CSe
    driverClassName: com.mysql.cj.jdbc.Driver
fileHome: /www